name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-java-build.yml
    with:
      java-version: '17'
      build-tool: 'maven'
